python train.py --bert_dir bert-base-cased \
            --lr 1e-5 \
            --multi_gpu False \
            --dataset NYT \
            --batch_size 8 \
            --max_epoch 100 \
            --test_epoch 1 \
            --train_prefix train_triples \
            --dev_prefix dev_triples \
            --test_prefix test_triples \
            --max_len 150 \
            --rel_num 24 \
            --period 500 \
            --seed 12 \
            --theta 0.5 \
            --debug True